### ISSUE TITLE
LDAP login works, but wekan user creation fails

### ISSUE THREAD

**Issue by weeeezzll** [wekan/wekan-ldap#16]
I'm using the docker-compose.yml linked to from LDAP wiki page (https://github.com/wekan/wekan/wiki/LDAP)

When I attempt to login with a user that doesn't exist I don't get any error message on the page, only the following log output on the console:

wekan-app  | [INFO] Init LDAP login "testuser"
wekan-app  | [WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL
wekan-app  | [INFO] Init setup
wekan-app  | [INFO] Connecting "ldap://domain.com:389"
wekan-app  | [DEBUG] connectionOptions{ url: 'ldap://domain.com:389',
wekan-app  |   timeout: 10000,
wekan-app  |   connectTimeout: 10000,
wekan-app  |   idleTimeout: 10000,
wekan-app  |   reconnect: true,
wekan-app  |   log:
wekan-app  |    Logger {
wekan-app  |      domain: null,
wekan-app  |      _events: {},
wekan-app  |      _eventsCount: 0,
wekan-app  |      _maxListeners: undefined,
wekan-app  |      _level: 30,
wekan-app  |      streams: [ [Object] ],
wekan-app  |      serializers: null,
wekan-app  |      src: false,
wekan-app  |      fields:
wekan-app  |       { name: 'ldapjs',
wekan-app  |         component: 'client',
wekan-app  |         hostname: '280fdd031117',
wekan-app  |         pid: 1 } } }
wekan-app  | [INFO] LDAP connected
wekan-app  | [INFO] Binding UserDN "CN=Admin\\, System,OU=Users,OU=TEST,DC=domain,DC=com"
wekan-app  | [INFO] Searching user "testuser"
wekan-app  | [DEBUG] searchOptions {
wekan-app  |   "filter": "(&(sAMAccountName=testuser))",
wekan-app  |   "scope": "sub",
wekan-app  |   "sizeLimit": 0
wekan-app  | }
wekan-app  | [DEBUG] BaseDN "OU=TEST,DC=domain,DC=com"
wekan-app  | [INFO] Search result count 1
wekan-app  | [INFO] Authenticating "CN=testuser,OU=TEST,DC=domain,DC=com"
wekan-app  | [INFO] Authenticated "CN=testuser,OU=TEST,DC=domain,DC=com"
wekan-app  | [DEBUG] Identifying user with: sAMAccountName
wekan-app  | [INFO] Querying user
wekan-app  | [DEBUG] userQuery {
wekan-app  |   "services.ldap.id": "4c5653514c531234567890653137"
wekan-app  | }
wekan-app  | [DEBUG] userQuery {
wekan-app  |   "username": "testuser"
wekan-app  | }
wekan-app  | [INFO] User does not exist, creating "testuser"
wekan-app  | [DEBUG] Identifying user with: sAMAccountName
wekan-app  | Exception while invoking method 'login' SyntaxError: Unexpected token m in JSON at position 14
wekan-app  |     at JSON.parse (<anonymous>)
wekan-app  |     at getDataToSyncUserData (packages/wekan:wekan-ldap/server/sync.js:116:27)
wekan-app  |     at addLdapUser (packages/wekan:wekan-ldap/server/sync.js:229:20)
wekan-app  |     at DDPCommon.MethodInvocation.<anonymous> (packages/wekan:wekan-ldap/server/loginHandler.js:159:18)
wekan-app  |     at packages/accounts-base/accounts_server.js:468:32
wekan-app  |     at tryLoginMethod (packages/accounts-base/accounts_server.js:245:14)
wekan-app  |     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:465:18)
wekan-app  |     at DDPCommon.MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:528:27)
wekan-app  |     at packages/check.js:128:16
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
wekan-app  |     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
wekan-app  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
wekan-app  |     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
wekan-app  |     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)

If I create a user in wekan with a matching corresponding LDAP user, there is no error on the page, and also no log output.  I can still login using the builtin authentication method though.

Based on the following error I'm assuming that some part of the LDAP data is causing the JSON to be malformed, but i'm not sure how to get wekan to spit out the details so I can track it down:
**Unexpected token m in JSON at position 14**

**Comment by weeeezzll** [comment]
I have a typo in the LDAP_SYNC_USER_DATA_FIELDMAP parameter.  After fixing that, everything is working correctly.
